on:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: containerapp01-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: containers-environment
  RESOURCE_GROUP: DefaultResourceGroup-CUS
  CONTAINER_REGISTRY_NAME: mregisregistry
  CONTAINER_REGISTRY_LOGIN_SERVER: mregisregistry.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.containers_environment_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.mregisregistry_USERNAME_85B7 }}
        acrPassword: ${{ secrets.mregisregistry_PASSWORD_85B7 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
